### ISSUE TITLE
create .yml for ICD-10 code values J00-J99

### ISSUE THREAD

**Issue by KaurMahima** [NSAPH-Data-Processing/medpar_outcomes#28]
- As part of the data request for the project titled 'Addressing Spatial Confounding in Air Pollution Studies', we need to filter and extract ICD-10 codes from the range J00 to J99 from the Medicare dataset. 
- The output will be saved in a .yml file for further analysis.

**Comment by audiracmichelle** [comment]
@audiracmichelle incorporate example without for loop
